// Indica que o arquivo é para ser renderizado no lado do cliente
"use client";

import { useEffect, useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "./Footer";
import ThemeProvider from "./providers/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Definir os metadados corretamente usando a função head
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null;
  }

  return (
    <ClerkProvider>
      {/* Definição das tags <html> e <body> */}
      <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
        <head>
          {/* Aqui você pode definir os metadados do layout */}
          <meta name="description" content="Generated by create next app" />
          <meta name="title" content="Create Next App" />
          <title>Create Next App</title>
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
